package com.paradigmas.tpfinalventas.ui.abm;

import com.paradigmas.tpfinalventas.controladores.ClienteControlador;
import com.paradigmas.tpfinalventas.controladores.FacturaControlador;
import com.paradigmas.tpfinalventas.controladores.FormaPagoControlador;
import com.paradigmas.tpfinalventas.controladores.ProductoControlador;
import com.paradigmas.tpfinalventas.objetos.Cliente;
import com.paradigmas.tpfinalventas.objetos.Factura;
import com.paradigmas.tpfinalventas.objetos.FormaPago;
import com.paradigmas.tpfinalventas.objetos.LineaFactura;
import com.paradigmas.tpfinalventas.objetos.Producto;
import com.paradigmas.tpfinalventas.ui.grilla.FacturaGrilla;
import com.paradigmas.tpfinalventas.ui.grilla.LineaGrilla;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

public class AbmFactura extends javax.swing.JPanel {
    
    private static final Logger LOGGER = Logger.getLogger(AbmFactura.class.getName());

    private final FacturaControlador facturaControlador;
    private final ProductoControlador productoControlador;
    private final ClienteControlador clienteControlador;
    private final FormaPagoControlador formaPagoControlador;

    private List<LineaFactura> lineasFacturaActual;
    private double totalFacturaActual = 0.0;
    
    public AbmFactura() {
        initComponents();
        
        facturaControlador = new FacturaControlador();
        productoControlador = new ProductoControlador();
        clienteControlador = new ClienteControlador();
        formaPagoControlador = new FormaPagoControlador();

        lineasFacturaActual = new ArrayList<>();
        
        configurarComponentes();
        cargarDatosIniciales();
    }
    
    private void configurarComponentes() {
        SpinnerNumberModel spinnerModel = new SpinnerNumberModel(1, 1, 1000, 1);
        cantidadSeleccionada.setModel(spinnerModel);
        jtLineaFactura.setModel(new LineaGrilla(new ArrayList<>()));
        
    }

    private void cargarDatosIniciales() {
        cargarClientesEnComboBox();
        cargarFormasPagoEnComboBox();
        cargarProductosEnComboBox();
        refreshTableFacturas();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        clienteSelected = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        formaPagoSelected = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        inputObservacion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        productoSelected = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cantidadSeleccionada = new javax.swing.JSpinner();
        btnAddLinea = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtLineaFactura = new javax.swing.JTable();
        btnCrearFactura = new javax.swing.JButton();
        btnEliminarLinea = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtFactura = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADMINISTRACION DE FACTURAS");

        jLabel2.setText("Cliente");

        jLabel3.setText("Forma de Pago");

        jLabel4.setText("Observaciones");

        jLabel5.setText("Producto");

        jLabel6.setText("Cantidad");

        btnAddLinea.setBackground(new java.awt.Color(51, 153, 255));
        btnAddLinea.setForeground(new java.awt.Color(255, 255, 255));
        btnAddLinea.setText("Agregar Producto");
        btnAddLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddLineaActionPerformed(evt);
            }
        });

        jLabel7.setText("DETALLE FACTURA ACTUAL");

        jtLineaFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtLineaFactura);

        btnCrearFactura.setBackground(new java.awt.Color(51, 153, 255));
        btnCrearFactura.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCrearFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearFactura.setText("GUARDAR FACTURA");
        btnCrearFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearFacturaActionPerformed(evt);
            }
        });

        btnEliminarLinea.setBackground(new java.awt.Color(51, 153, 255));
        btnEliminarLinea.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarLinea.setText("Quitar Producto");
        btnEliminarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarLineaActionPerformed(evt);
            }
        });

        labelTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotal.setText("TOTAL:");

        jtFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtFactura);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(479, 479, 479))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(productoSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clienteSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formaPagoSelected, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cantidadSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminarLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearFactura)
                    .addComponent(labelTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clienteSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(formaPagoSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(btnAddLinea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productoSelected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidadSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarLinea)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator1))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCrearFactura)
                        .addGap(95, 95, 95)
                        .addComponent(labelTotal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarLineaActionPerformed
        int filaSeleccionada = jtLineaFactura.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una linea de producto para eliminar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        lineasFacturaActual.remove(filaSeleccionada);
        actualizarTablaLineas();
        actualizarTotal();
    }//GEN-LAST:event_btnEliminarLineaActionPerformed

    private void btnCrearFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearFacturaActionPerformed
        Cliente cliente = (Cliente) clienteSelected.getSelectedItem();
        FormaPago formaPago = (FormaPago) formaPagoSelected.getSelectedItem();

        if (cliente == null || formaPago == null) {
            JOptionPane.showMessageDialog(this, "Cliente y Forma de Pago son obligatorios.", "Error de Validacion", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (lineasFacturaActual.isEmpty()) {
            JOptionPane.showMessageDialog(this, "La factura debe tener al menos una linea.", "Error de Validacion", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Factura nuevaFactura = new Factura();
        nuevaFactura.setCliente(cliente);
        nuevaFactura.setFormaDePago(formaPago);
        nuevaFactura.setFecha(new Date());
        nuevaFactura.setLineaFactura(lineasFacturaActual);
        nuevaFactura.setTotal(totalFacturaActual);
        nuevaFactura.setObservaciones("");

        boolean exito = facturaControlador.crear(nuevaFactura);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Factura creada exitosamente.", "Exito", JOptionPane.INFORMATION_MESSAGE);
            limpiarFormulario();
            refreshTableFacturas();
        } else {
            JOptionPane.showMessageDialog(this, "Error al crear la factura.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearFacturaActionPerformed

    private void btnAddLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddLineaActionPerformed
        Producto producto = (Producto) productoSelected.getSelectedItem();
        int cantidadInt = (int) cantidadSeleccionada.getValue();

        if (producto == null) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un producto.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double cantidadDouble = (double) cantidadInt;
        double subtotal = (double) (producto.getPrecio() * cantidadInt);

        LineaFactura nuevaLinea = new LineaFactura();
        nuevaLinea.setProducto(producto);
        nuevaLinea.setCantidad(cantidadDouble);
        nuevaLinea.setSubtotal(subtotal);

        lineasFacturaActual.add(nuevaLinea);

        actualizarTablaLineas();
        actualizarTotal();
    }//GEN-LAST:event_btnAddLineaActionPerformed

    private void cargarProductosEnComboBox() {
        try {
            List<Producto> productos = productoControlador.listar();
            DefaultComboBoxModel<Producto> model = new DefaultComboBoxModel<>(productos.toArray(new Producto[0]));
            productoSelected.setModel(model);
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, "Error al cargar productos", ex);
        }
    }

    private void cargarClientesEnComboBox() {
        try {
            List<Cliente> clientes = clienteControlador.listar();
            DefaultComboBoxModel<Cliente> model = new DefaultComboBoxModel<>(clientes.toArray(new Cliente[0]));
            clienteSelected.setModel(model);
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, "Error al cargar clientes", ex);
        }
    }

    private void cargarFormasPagoEnComboBox() {
        try {
            List<FormaPago> formasPago = formaPagoControlador.listar();
            DefaultComboBoxModel<FormaPago> model = new DefaultComboBoxModel<>(formasPago.toArray(new FormaPago[0]));
            formaPagoSelected.setModel(model);
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, "Error al cargar formas de pago", ex);
        }
    }

    private void refreshTableFacturas() {
        try {
            List<Factura> facturas = facturaControlador.listar();
            jtFactura.setModel(new FacturaGrilla(facturas));
        } catch (Exception ex) {
            LOGGER.log(Level.SEVERE, "Error al refrescar la tabla de facturas", ex);
        }
    }

    private void actualizarTablaLineas() {
        jtLineaFactura.setModel(new LineaGrilla(lineasFacturaActual));
    }

    private void actualizarTotal() {
        totalFacturaActual = 0.0;
        for (LineaFactura linea : lineasFacturaActual) {
            totalFacturaActual += linea.getSubtotal();
        }
        labelTotal.setText(String.format("TOTAL: $ %.2f", totalFacturaActual));
    }

    private void limpiarFormulario() {
        if (clienteSelected.getItemCount() > 0) clienteSelected.setSelectedIndex(0);
        if (formaPagoSelected.getItemCount() > 0) formaPagoSelected.setSelectedIndex(0);
        lineasFacturaActual.clear();
        actualizarTablaLineas();
        actualizarTotal();
        cantidadSeleccionada.setValue(1);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddLinea;
    private javax.swing.JButton btnCrearFactura;
    private javax.swing.JButton btnEliminarLinea;
    private javax.swing.JSpinner cantidadSeleccionada;
    private javax.swing.JComboBox<Cliente> clienteSelected;
    private javax.swing.JComboBox<FormaPago> formaPagoSelected;
    private javax.swing.JTextField inputObservacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jtFactura;
    private javax.swing.JTable jtLineaFactura;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JComboBox<Producto> productoSelected;
    // End of variables declaration//GEN-END:variables
}
