package com.paradigmas.tpfinalventas.ui.abm;

import com.paradigmas.tpfinalventas.controladores.CategoriaControlador;
import com.paradigmas.tpfinalventas.controladores.ProductoControlador;
import com.paradigmas.tpfinalventas.objetos.Categoria;
import com.paradigmas.tpfinalventas.objetos.Producto;
import com.paradigmas.tpfinalventas.ui.grilla.GrillaProducto;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


public class AbmProducto extends javax.swing.JPanel {
    
    private final ProductoControlador productoControlador;
    private final CategoriaControlador categoriaControlador;
    
    public AbmProducto() {
        initComponents();
        
        productoControlador = new ProductoControlador();
        categoriaControlador = new CategoriaControlador();
        
        cargarCategoriasEnComboBox();
        
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textMain = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        labelDescripcion = new javax.swing.JLabel();
        inputDescripcion = new javax.swing.JTextField();
        inputPrecio = new javax.swing.JTextField();
        labelPrecio = new javax.swing.JLabel();
        labelCategoria = new javax.swing.JLabel();
        itemsCategoria = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jtListaProductos = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        labelCategoriaProducto = new javax.swing.JLabel();
        labelNombreCategoria = new javax.swing.JLabel();
        labelDescripcionCategoria = new javax.swing.JLabel();
        inputDescripcionCategoria = new javax.swing.JTextField();
        inputNombreCategoria = new javax.swing.JTextField();
        btnAgregarCategoria = new javax.swing.JButton();
        textMain1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        textMain.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textMain.setText("ABM PRODUCTOS");

        labelNombre.setText("Nombre");

        labelDescripcion.setText("Descripcion");

        labelPrecio.setText("Precio");

        labelCategoria.setText("Categoria");

        btnAgregar.setBackground(new java.awt.Color(51, 153, 255));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimpiar.setBackground(new java.awt.Color(51, 153, 255));
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(51, 153, 255));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(51, 153, 255));
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtProductos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProductosMouseClicked(evt);
            }
        });
        jtListaProductos.setViewportView(jtProductos);

        labelCategoriaProducto.setText("NUEVA CATEGORIA");

        labelNombreCategoria.setText("Nombre");

        labelDescripcionCategoria.setText("Descripcion");

        btnAgregarCategoria.setBackground(new java.awt.Color(51, 153, 255));
        btnAgregarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarCategoria.setText("AGREGAR");
        btnAgregarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCategoriaActionPerformed(evt);
            }
        });

        textMain1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textMain1.setText("LISTA DE PRODUCTOS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(textMain))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(inputDescripcion))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(inputNombre))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(28, 28, 28)
                                            .addComponent(inputPrecio))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(labelCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                            .addComponent(itemsCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(35, 35, 35))
                            .addComponent(btnAgregarCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelDescripcionCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(inputDescripcionCategoria))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(labelNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(28, 28, 28)
                                    .addComponent(inputNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(labelCategoriaProducto)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                        .addComponent(textMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(256, 256, 256))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(23, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textMain)
                    .addComponent(textMain1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombre)
                            .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDescripcion)
                            .addComponent(inputDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPrecio)
                            .addComponent(inputPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCategoria)
                            .addComponent(itemsCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnLimpiar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificar)
                            .addComponent(btnEliminar))
                        .addGap(32, 32, 32)
                        .addComponent(labelCategoriaProducto)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreCategoria)
                            .addComponent(inputNombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDescripcionCategoria)
                            .addComponent(inputDescripcionCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarCategoria))
                    .addComponent(jtListaProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        Producto nuevoProducto = new Producto();
        nuevoProducto.setNombre(inputNombre.getText());
        nuevoProducto.setDescripcion(inputDescripcion.getText());
        
        try {
            nuevoProducto.setPrecio(Float.valueOf(inputPrecio.getText()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        nuevoProducto.setCategoria((Categoria)itemsCategoria.getSelectedItem());
        nuevoProducto.setFechaCreacion(new java.util.Date());

        if (productoControlador.crear(nuevoProducto)) {
            JOptionPane.showMessageDialog(this, "Producto agregado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            refreshTable();
            resetFields();
        } else {
            JOptionPane.showMessageDialog(this, "Error al agregar el producto.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        resetFields();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int filaSeleccionada = jtProductos.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                this, 
                "Por favor, seleccione un producto de la tabla para eliminar.", 
                "Acción Requerida", 
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(
            this,
            "¿Está seguro de que desea eliminar este producto?",
            "Confirmar Eliminación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (confirmacion != JOptionPane.YES_OPTION) {
            return;
        }

        Integer idProducto = (Integer) jtProductos.getModel().getValueAt(filaSeleccionada, 0);
        
        Producto productoAEliminar = new Producto();
        productoAEliminar.setId(idProducto);

        boolean exito = productoControlador.eliminar(productoAEliminar);

        if (exito) {
            JOptionPane.showMessageDialog(
                this, 
                "Producto eliminado exitosamente.", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE
            );
            refreshTable();    
            resetFields();     
        } else {
            JOptionPane.showMessageDialog(
                this, 
                "Error al eliminar el producto. Es posible que esté asociado a una factura.", 
                "Error de Eliminación", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int filaSeleccionada = jtProductos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(
                this,
                "Por favor, seleccione un producto de la tabla para modificar.",
                "Acción Requerida",
                JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        Integer idProducto = (Integer) jtProductos.getModel().getValueAt(filaSeleccionada, 0);

        String nombre = inputNombre.getText();
        String descripcion = inputDescripcion.getText();
        String precioStr = inputPrecio.getText();
        Categoria categoria = (Categoria) itemsCategoria.getSelectedItem();

        if (nombre.trim().isEmpty() || descripcion.trim().isEmpty() || precioStr.trim().isEmpty() || categoria == null) {
            JOptionPane.showMessageDialog(
                this,
                "Todos los campos (Nombre, Descripción, Precio y Categoría) son obligatorios.",
                "Error de Validación",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        Producto productoModificado = new Producto();
        productoModificado.setId(idProducto); 
        productoModificado.setNombre(nombre);
        productoModificado.setDescripcion(descripcion);
        productoModificado.setCategoria(categoria);
        
        Producto productoOriginal = productoControlador.extraer(idProducto);
        if (productoOriginal != null) {
            productoModificado.setFechaCreacion(productoOriginal.getFechaCreacion());
        } else {
            JOptionPane.showMessageDialog(this, "Error: No se encontró el producto original para modificar.", "Error Crítico", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            productoModificado.setPrecio(Float.parseFloat(precioStr));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El precio debe ser un número válido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean exito = productoControlador.modificar(productoModificado);

        if (exito) {
            JOptionPane.showMessageDialog(
                this,
                "Producto modificado exitosamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
            refreshTable();    
            resetFields();     
        } else {
            JOptionPane.showMessageDialog(
                this,
                "Error al modificar el producto.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnAgregarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCategoriaActionPerformed
        String nombreCategoria = inputNombreCategoria.getText();
        String descripcionCategoria = inputDescripcionCategoria.getText();

        if (nombreCategoria.trim().isEmpty()) {
            JOptionPane.showMessageDialog(
                this,
                "El nombre de la categoría no puede estar vacío.",
                "Error de Validación",
                JOptionPane.ERROR_MESSAGE
            );
            return;
        }
        
        Categoria nuevaCategoria = new Categoria();
        nuevaCategoria.setDenominacion(nombreCategoria);
        nuevaCategoria.setDescripcion(descripcionCategoria);

        boolean exito = categoriaControlador.crear(nuevaCategoria);

        if (exito) {
            JOptionPane.showMessageDialog(
                this,
                "Categoría agregada exitosamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
            );
            cargarCategoriasEnComboBox();
            inputNombreCategoria.setText("");
            inputDescripcionCategoria.setText("");
        } else {
            JOptionPane.showMessageDialog(
                this,
                "Error al agregar la categoría. Es posible que ya exista una con el mismo nombre.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_btnAgregarCategoriaActionPerformed

    private void jtProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProductosMouseClicked
        int filaSeleccionada = jtProductos.getSelectedRow();
        
        if (filaSeleccionada == -1) {
            return;
        }

        Integer idProducto = (Integer) jtProductos.getModel().getValueAt(filaSeleccionada, 0);

        Producto productoSeleccionado = productoControlador.extraer(idProducto);
        
        if (productoSeleccionado != null) {
            inputNombre.setText(productoSeleccionado.getNombre());
            inputDescripcion.setText(productoSeleccionado.getDescripcion());
            inputPrecio.setText(String.valueOf(productoSeleccionado.getPrecio()));

            Categoria categoriaDelProducto = productoSeleccionado.getCategoria();
            DefaultComboBoxModel<Categoria> model = (DefaultComboBoxModel<Categoria>) itemsCategoria.getModel();
        
            for (int i = 0; i < model.getSize(); i++) {
                if (model.getElementAt(i).getId().equals(categoriaDelProducto.getId())) {
                    itemsCategoria.setSelectedIndex(i);
                    break;
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se pudieron cargar los datos del producto.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jtProductosMouseClicked

    private void resetFields(){
        inputNombre.setText("");
        inputDescripcion.setText("");
        inputPrecio.setText("");
        if (itemsCategoria.getItemCount() > 0) {
            itemsCategoria.setSelectedIndex(0);
        }
        jtProductos.clearSelection();
    }

    private void refreshTable(){
        try {
            List<Producto> productos = productoControlador.listar();
            jtProductos.setModel(new GrillaProducto((ArrayList<Producto>) productos));
        } catch (Exception ex) {
            Logger.getLogger(AbmProducto.class.getName()).log(Level.SEVERE, "Error al refrescar la tabla de productos", ex);
        }
    }
    
    private void cargarCategoriasEnComboBox() {
        try {
            List<Categoria> categorias = categoriaControlador.listar();
            DefaultComboBoxModel<Categoria> modelCombo = new DefaultComboBoxModel<>(categorias.toArray(new Categoria[0]));
            itemsCategoria.setModel(modelCombo);
        } catch (Exception ex) {
            Logger.getLogger(AbmProducto.class.getName()).log(Level.SEVERE, "Error al cargar categorías en el ComboBox", ex);
            JOptionPane.showMessageDialog(this, "Error al cargar las categorías.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarCategoria;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JTextField inputDescripcion;
    private javax.swing.JTextField inputDescripcionCategoria;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNombreCategoria;
    private javax.swing.JTextField inputPrecio;
    private javax.swing.JComboBox<Categoria> itemsCategoria;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jtListaProductos;
    private javax.swing.JTable jtProductos;
    private javax.swing.JLabel labelCategoria;
    private javax.swing.JLabel labelCategoriaProducto;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelDescripcionCategoria;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreCategoria;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel textMain;
    private javax.swing.JLabel textMain1;
    // End of variables declaration//GEN-END:variables
}
